export const bookCategories = [
  "Fiction",
  "Non-Fiction",
  "Mystery/Thriller/Crime",
  "Science Fiction/Fantasy",
  "Romance",
  "Historical Fiction",
  "Adventure",
  "Biography/Memoir",
  "Self-Help/Personal Development",
  "Health/Fitness",
  "Psychology",
  "Business/Economics",
  "Science/Nature",
  "Travel",
  "Cooking/Food",
  "History",
  "Politics/Social Sciences",
  "Children's",
  "Young Adult",
  "Educational/Textbooks",
  "Rare/Collectible",
  "Art/Photography",
  "Gardening",
  "Religion/Spirituality",
  "Poetry",
];
